# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2db7b2019f681f04cbe4a694b70550ba"
name = "Wholesale"
handle = "wholesale"
application_url = "https://jm-wholesale.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, read_discounts"

[auth]
redirect_urls = [ "https://jm-wholesale.vercel.app/auth/callback" ]
